# Generated by Django 4.2.7 on 2026-04-20 15:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('source_service', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('search', 'Search'), ('view_product', 'View Product'), ('add_to_cart', 'Add To Cart'), ('update_cart_quantity', 'Update Cart Quantity'), ('remove_from_cart', 'Remove From Cart'), ('purchase', 'Purchase')], max_length=32)),
                ('product_service', models.CharField(blank=True, choices=[('cloth', 'Cloth'), ('laptop', 'Laptop'), ('mobile', 'Mobile'), ('accessory', 'Tech Accessories'), ('home-appliance', 'Home Appliances'), ('book', 'Books'), ('beauty', 'Beauty'), ('food', 'Food & Drinks'), ('sports', 'Sports'), ('gaming', 'Gaming')], max_length=20)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('search_keyword', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['user_id', 'occurred_at'], name='events_beha_user_id_884afb_idx'), models.Index(fields=['event_type', 'occurred_at'], name='events_beha_event_t_03a083_idx'), models.Index(fields=['source_service', 'occurred_at'], name='events_beha_source__d2d8de_idx')],
            },
        ),
    ]
